// src/components/Shipments/shipmentsData.ts
import { Shipment } from "@/types/shipment";

const shipmentsData: Shipment[] = [
  {
    id: "1",
    title: "Toyota Corolla",
    model: "Sedan",
    year: 2019,
    destination: "Australia",
    cover: "/images/shipments/toyota-corolla-aus/1.png",
    images: [
      "/images/shipments/toyota-corolla-aus/1.png",
      "/images/shipments/toyota-corolla-aus/2.png",
      "/images/shipments/toyota-corolla-aus/3.png",
      "/images/shipments/toyota-corolla-aus/4.png",
    ],
  },
    {
    id: "2",
    title: "Audi A3",
    model: "Sports back",
    year: 2015,
    destination: "UK",
    cover: "/images/shipments/audi-a3-uk1/1.jpg",
    images: [
      "/images/shipments/audi-a3-uk1/1.jpg",
      "/images/shipments/audi-a3-uk1/2.jpg",
      "/images/shipments/audi-a3-uk1/3.jpg",
      "/images/shipments/audi-a3-uk1/4.jpg",
      "/images/shipments/audi-a3-uk1/5.jpg",
    ],
  },
  
  {
    id: "3",
    title: "Nissan Diesel Tanker",
    model: "",
    year: 2001,
    destination: "Tanzania",
    cover: "/images/shipments/nissan-truck-tanzania/1.png",
    images: [
      "/images/shipments/nissan-truck-tanzania/1.png",
      "/images/shipments/nissan-truck-tanzania/2.png",
      "/images/shipments/nissan-truck-tanzania/3.png",
    ],
  },
  {
    id: "4",
    title: "Toyota Estima Hybrid",
    model: "Aeras Premium",
    year: 2018,
    destination: "UK",
    cover: "/images/shipments/toyota-estima-uk1/1.png",
    images: [
      "/images/shipments/toyota-estima-uk1/1.png",
      "/images/shipments/toyota-estima-uk1/2.png",
      "/images/shipments/toyota-estima-uk1/3.png",
      "/images/shipments/toyota-estima-uk1/4.png",
      "/images/shipments/toyota-estima-uk1/5.png",
    ],
  },
  {
    id: "5",
    title: "Toyota Raize",
    model: "G grade",
    year: 2020,
    destination: "Pakistan",
    cover: "/images/shipments/toyota-raize-pk1/1.png",
    images: [
      "/images/shipments/toyota-raize-pk1/1.png",
      "/images/shipments/toyota-raize-pk1/2.png",
      "/images/shipments/toyota-raize-pk1/3.png",
      "/images/shipments/toyota-raize-pk1/4.png",
      "/images/shipments/toyota-raize-pk1/5.png",
      "/images/shipments/toyota-raize-pk1/6.png",
      "/images/shipments/toyota-raize-pk1/7.png",
    ],
  },
  {
    id: "6",
    title: "Lexus LX 570",
    model: "",
    year: 2017,
    destination: "UK",
    cover: "/images/shipments/lexus-lx570-uk1/1.jpg",
    images: [
      "/images/shipments/lexus-lx570-uk1/1.jpg",
      "/images/shipments/lexus-lx570-uk1/2.png",
      "/images/shipments/lexus-lx570-uk1/3.png",
      "/images/shipments/lexus-lx570-uk1/4.jpg",
      "/images/shipments/lexus-lx570-uk1/5.png",
      "/images/shipments/lexus-lx570-uk1/6.png",
      "/images/shipments/lexus-lx570-uk1/7.jpg",
    ],
  },
  {
    id: "7",
    title: "Toyota Tacoma",
    model: "4WD",
    year: 2006,
    destination: "UAE",
    cover: "/images/shipments/toyota-tacoma-uae/1.png",
    images: [
      "/images/shipments/toyota-tacoma-uae/1.png",
      "/images/shipments/toyota-tacoma-uae/2.png",
      "/images/shipments/toyota-tacoma-uae/3.png",
      "/images/shipments/toyota-tacoma-uae/4.png",
      "/images/shipments/toyota-tacoma-uae/5.png",
    ],
  },
  {
    id: "8",
    title: "Toyota Prius Alpha",
    model: "S Tune Black II",
    year: 2018,
    destination: "UK",
    cover: "/images/shipments/prius-alpha-uk1/1.png",
    images: [
      "/images/shipments/prius-alpha-uk1/1.png",
      "/images/shipments/prius-alpha-uk1/2.png",
      "/images/shipments/prius-alpha-uk1/3.png",
      "/images/shipments/prius-alpha-uk1/4.png",
      "/images/shipments/prius-alpha-uk1/5.png",
    ],
  },
  {
    id: "9",
    title: "Toyota Estima Hybrid",
    model: "Aeras Smart",
    year: 2018,
    destination: "UK",
    cover: "/images/shipments/toyota-estima-uk2/1.png",
    images: [
      "/images/shipments/toyota-estima-uk2/1.png",
      "/images/shipments/toyota-estima-uk2/2.png",
      "/images/shipments/toyota-estima-uk2/3.png",
      "/images/shipments/toyota-estima-uk2/4.png",
    ],
  },
  {
    id: "10",
    title: "Toyota Voxy Hybrid",
    model: "X",
    year: 2020,
    destination: "UK",
    cover: "/images/shipments/toyota-voxy-uk1/1.png",
    images: [
      "/images/shipments/toyota-voxy-uk1/1.png",
      "/images/shipments/toyota-voxy-uk1/2.png",
      "/images/shipments/toyota-voxy-uk1/3.png",
    ],
  },
  {
    id: "11",
    title: "Toyota Corolla Touring Hybrid",
    model: "",
    year: 2020,
    destination: "UK",
    cover: "/images/shipments/toyota-corolla-touring-uk1/1.png",
    images: [
      "/images/shipments/toyota-corolla-touring-uk1/1.png",
      "/images/shipments/toyota-corolla-touring-uk1/2.png",
      "/images/shipments/toyota-corolla-touring-uk1/3.png",
      "/images/shipments/toyota-corolla-touring-uk1/4.png",
      "/images/shipments/toyota-corolla-touring-uk1/5.png",
      "/images/shipments/toyota-corolla-touring-uk1/6.png",
    ],
  },
  {
    id: "12",
    title: "Honda Fit Hybrid",
    model: "GP5",
    year: 2014,
    destination: "UK",
    cover: "/images/shipments/honda-fit-uk1/1.png",
    images: [
      "/images/shipments/honda-fit-uk1/1.png",
      "/images/shipments/honda-fit-uk1/2.png",
      "/images/shipments/honda-fit-uk1/3.png",
      "/images/shipments/honda-fit-uk1/4.png",
      "/images/shipments/honda-fit-uk1/5.png",
    ],
  },
  {
    id: "13",
    title: "Nissan Note e-Power",
    model: "X-V",
    year: 2019,
    destination: "Pakistan",
    cover: "/images/shipments/nissan-note-pk1/1.jpg",
    images: [
      "/images/shipments/nissan-note-pk1/1.jpg",
      "/images/shipments/nissan-note-pk1/2.jpg",
      "/images/shipments/nissan-note-pk1/3.jpg",
      "/images/shipments/nissan-note-pk1/4.jpg",
      "/images/shipments/nissan-note-pk1/5.jpg",
      "/images/shipments/nissan-note-pk1/6.jpg",
    ],
  },
  {
    id: "14",
    title: "Toyota CH-R Hybrid",
    model: "G-LED",
    year: 2017,
    destination: "Pakistan",
    cover: "/images/shipments/toyota-chr-pk1/1.jpg",
    images: [
      "/images/shipments/toyota-chr-pk1/1.jpg",
      "/images/shipments/toyota-chr-pk1/2.jpg",
      "/images/shipments/toyota-chr-pk1/3.jpg",
      "/images/shipments/toyota-chr-pk1/4.jpg",
      "/images/shipments/toyota-chr-pk1/5.jpg",
      "/images/shipments/toyota-chr-pk1/6.jpg",
    ],
  },
  {
    id: "15",
    title: "Toyota Prius",
    model: "S Grade",
    year: 2019,
    destination: "UK",
    cover: "/images/shipments/toyota-prius-uk1/1.jpg",
    images: [
      "/images/shipments/toyota-prius-uk1/1.jpg",
      "/images/shipments/toyota-prius-uk1/2.jpg",
      "/images/shipments/toyota-prius-uk1/3.jpg",
      "/images/shipments/toyota-prius-uk1/4.jpg",
      "/images/shipments/toyota-prius-uk1/5.jpg",
    ],
  },
  {
    id: "16",
    title: "Toyota CH-R",
    model: "",
    year: 2019,
    destination: "Tanzania",
    cover: "/images/shipments/toyota-chr-tanzania/1.jpg",
    images: [
      "/images/shipments/toyota-chr-tanzania/1.jpg",
      "/images/shipments/toyota-chr-tanzania/2.jpg",
      "/images/shipments/toyota-chr-tanzania/3.jpg",
      "/images/shipments/toyota-chr-tanzania/4.jpg",
      "/images/shipments/toyota-chr-tanzania/5.jpg",
      "/images/shipments/toyota-chr-tanzania/6.jpg",
      "/images/shipments/toyota-chr-tanzania/7.jpg",
    ],
  },
  {
    id: "17",
    title: "Toyota Noah Hybrid",
    model: "",
    year: 2019,
    destination: "UK",
    cover: "/images/shipments/toyota-noah-uk1/1.jpg",
    images: [
      "/images/shipments/toyota-noah-uk1/1.jpg",
      "/images/shipments/toyota-noah-uk1/2.jpg",
      "/images/shipments/toyota-noah-uk1/3.jpg",
      "/images/shipments/toyota-noah-uk1/4.jpg",
      "/images/shipments/toyota-noah-uk1/5.jpg",
    ],
  },
];

export default shipmentsData;
