// src/components/Shipments/shipmentsData.ts
import { Shipment } from "@/types/shipment";

const shipmentsData: Shipment[] = [

  {
    "id": "3",
    "title": "Heavy Machinery Shipment",
    "model": "",
    "year": 1111,
    "destination": "Lebanon",
    "cover": "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068046.jpg",
    "images": [
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068046.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068047.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068050.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068053.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068055.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068063.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068064.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068065.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068088.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068095.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068104.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068109.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068110.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068111.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068128.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068130.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068136.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068140.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068141.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068143.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068147.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068158.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068159.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068160.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068161.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068162.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068163.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068170.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068172.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068174.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068175.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068177.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068179.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068183.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068185.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068186.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068190.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068191.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068192.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068196.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068197.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068198.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068199.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068200.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068206.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068207.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068210.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068212.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068213.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068214.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068215.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068216.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068217.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068218.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068219.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068221.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068223.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068229.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068230.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068231.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068238.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068242.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068243.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068246.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068248.jpg",
      "https://uzbcwvdwfpkflcggeofg.supabase.co/storage/v1/object/public/rtweb/machinery/1000068250.jpg",
    ]
  },
]

export default shipmentsData;
